-- =====================================================================
-- migration_027 — descrições das tabelas para a tela "Banco de dados"
--   on conflict do nothing: se a descrição já foi editada na tela, não
--   é sobrescrita. REGRA: toda migration nova que criar tabela deve
--   inserir aqui (db_catalogo_tabelas) a descrição dela.
-- =====================================================================

insert into public.db_catalogo_tabelas (esquema, tabela, area, titulo, para_que, origem, usado_em) values
-- ---------- Espelho das planilhas (legado) ----------
('legado', 'planilhas', 'Espelho das planilhas', 'Planilhas das psicólogas',
 'Lista de todas as planilhas individuais (uma por psicóloga) que o sync lê: nome, aba, cabeçalho, quantas linhas, quando sincronizou, se foi desligada.',
 'Apps Script "Calculo RPA" → SyncSupabase.gs (sincronizarPlanilhasSupabase)',
 'Base de todo o espelho; Repasse (RPA), Registro de guias, BI'),
('legado', 'atendimentos_raw', 'Espelho das planilhas', 'Atendimentos (cópia crua)',
 'Cada linha da aba de atendimentos de cada psicóloga, exatamente como está na planilha (células em JSON). Fonte das sessões realizadas, faltas e guias lançadas.',
 'Apps Script SyncSupabase.gs → legacy_ingest_sheet',
 'Repasse (RPA), Guias não lançadas, Conferência, Projeção, BI (Dashboard, Psicólogas, Faltas, Planos)'),
('legado', 'bd_guias', 'Espelho das planilhas', 'BD_GUIAS (guias registradas)',
 'Cópia da aba BD_GUIAS: guias autorizadas/registradas. Comparada com os atendimentos para achar guias não lançadas.',
 'Apps Script SyncSupabase.gs',
 'Guias não lançadas, Gerar guias, BI'),
('legado', 'agenda', 'Espelho das planilhas', 'Agenda ativa',
 'Horários fixos de cada psicóloga (dia, horário, sala, plano, valor) já classificados: PACIENTE, LIVRE, BLOQUEADO, RESERVADO. Só campos de indicador (LGPD).',
 'Apps Script SyncSupabase.gs → legacy_ingest_agenda',
 'BI (Dashboard, Psicólogas, Perfil, Planos), Gerar guias'),
('legado', 'cancelados', 'Espelho das planilhas', 'Pacientes cancelados',
 'Aba Cancelados de cada psicóloga: quem saiu, quando, plano, faixa etária e cidade. Usada para taxa de cancelamento.',
 'Apps Script SyncSupabase.gs → legacy_ingest_agenda',
 'BI (Dashboard, Perfil)'),
('legado', 'salas_painel', 'Espelho das planilhas', 'Painel de salas',
 'Grade de ocupação das salas (dia × horário × consultório) copiada da planilha de agendamento de salas.',
 'Apps Script SyncSupabase.gs → legacy_ingest_salas (SALAS_SPREADSHEET_ID)',
 'BI → Agendamento de salas (resumo de ocupação)'),
('legado', 'salas_meta', 'Espelho das planilhas', 'Cabeçalho do painel de salas',
 'Nome das colunas (consultórios) do painel de salas e quando foi sincronizado.',
 'Apps Script SyncSupabase.gs → legacy_ingest_salas',
 'BI → Agendamento de salas'),
('legado', 'exencoes', 'Espelho das planilhas', 'Isenções / CNPJ das psicólogas',
 'Psicólogas que emitem como CNPJ (sem INSS) e o percentual de repasse delas.',
 'Apps Script SyncSupabase.gs → legacy_ingest_exencoes',
 'Repasse (RPA)'),
('legado', 'config', 'Espelho das planilhas', 'Configuração do sync',
 'Uma linha: qual clínica recebe os dados do sync e o hash do token que o Apps Script usa. O token nunca aparece nesta tela.',
 'Criada na instalação do sync', 'Todas as funções legacy_ingest_*'),
('legado', 'sync_log', 'Espelho das planilhas', 'Histórico do sync',
 'Uma linha por planilha recebida: quantas linhas, se deu certo e a mensagem de erro.',
 'Gravada automaticamente pelas funções legacy_ingest_*', 'Aviso de sincronização (BI e Financeiro)'),
('legado', 'registro_log', 'Espelho das planilhas', 'Histórico do Registro de guias',
 'O que a tela Registro de guias (HTML original) pediu e respondeu, para auditoria.',
 'Rota /financeiro/guias/api', 'Registro de guias'),

-- ---------- Faturamento de convênios ----------
('public', 'insurance_plans', 'Faturamento de convênios', 'Convênios / planos',
 'Cadastro dos convênios (Unimed, Bradesco, Select, GEAP, Celos…): valor da sessão, regra de pagamento (dias, base, dia útil), códigos ANS/prestador.',
 'Cadastro manual (migrations)', 'Agenda de recebimentos, Painel financeiro, Importar XML, Projeção'),
('public', 'claim_statements', 'Faturamento de convênios', 'Demonstrativos (XML TISS)',
 'Cada arquivo XML de demonstrativo de retorno importado: operadora, número, emissão e totais informado/liberado/glosa.',
 'Tela Importar XML → import_claim_statement', 'Notas fiscais, Painel financeiro, Conferência'),
('public', 'insurance_claim_returns', 'Faturamento de convênios', 'Itens dos demonstrativos',
 'Cada guia/sessão dentro dos demonstrativos: número da guia, data, valores informado/liberado/glosado, código da glosa. Nome e carteirinha ficam criptografados.',
 'Tela Importar XML', 'Conferência de guias, Divergências, Painel financeiro, Projeção'),
('public', 'claim_return_glosses', 'Faturamento de convênios', 'Glosas por item',
 'Glosas (código e valor) de cada item do demonstrativo.',
 'Tela Importar XML', 'Painel financeiro (glosas por código)'),
('public', 'claim_items_current', 'Faturamento de convênios', 'Itens atuais (visão)',
 'Visão: a versão mais recente de cada item faturado (quando o mesmo item aparece em mais de um demonstrativo).',
 'Calculada a partir de insurance_claim_returns', 'Conferência, Painel financeiro'),
('public', 'claim_monthly_summary', 'Faturamento de convênios', 'Resumo mensal (visão)',
 'Visão: por convênio e mês, sessões, informado, liberado, glosa e prazo até o demonstrativo.',
 'Calculada', 'Painel financeiro'),
('public', 'claim_gloss_by_code', 'Faturamento de convênios', 'Glosas por código (visão)',
 'Visão: total de glosa por código de glosa e convênio.', 'Calculada', 'Painel financeiro'),
('public', 'claim_statement_overview', 'Faturamento de convênios', 'Visão geral dos demonstrativos (visão)',
 'Visão: cada demonstrativo com itens, divergências, nota fiscal emitida, pago e situação financeira.',
 'Calculada', 'Notas fiscais, Painel financeiro'),
('public', 'operator_invoices', 'Faturamento de convênios', 'Notas fiscais para operadoras',
 'Notas emitidas contra cada demonstrativo: número, valor, previsão e data de pagamento.',
 'Tela Notas fiscais', 'Notas fiscais, Agenda de recebimentos, Projeção'),
('public', 'gloss_appeals', 'Faturamento de convênios', 'Recursos de glosa',
 'Acompanhamento de recurso de glosa por item: situação, valor recuperado, observações.',
 'Tela Conferência / Divergências', 'Divergências'),
('public', 'guides', 'Faturamento de convênios', 'Guias (sistema novo)',
 'Guias do sistema novo ligadas a sessões. Ainda vazia: hoje as guias vêm do espelho das planilhas.',
 'Futuro módulo de sessões', '—'),
('public', 'guide_status_overrides', 'Faturamento de convênios', 'Correções de situação de guia',
 'Quando alguém muda manualmente a situação de uma guia: antes, depois e motivo.',
 'Futuro módulo de guias', '—'),

-- ---------- Financeiro e banco ----------
('public', 'cashflow_items', 'Financeiro e banco', 'Itens do fluxo de caixa',
 'Recebimentos e pagamentos previstos/realizados (lotes Orizon, previstos dos demonstrativos, lançamentos manuais).',
 'Importar (Orizon), previstos_demonstrativos_sync, tela Agenda de recebimentos', 'Agenda de recebimentos, Painel financeiro, Projeção, DRE'),
('public', 'cashflow_imports', 'Financeiro e banco', 'Importações do fluxo de caixa',
 'Cada arquivo importado para o fluxo de caixa: nome, hash, linhas novas/atualizadas.',
 'Tela Importar', 'Importar'),
('public', 'cashflow_calendar', 'Financeiro e banco', 'Calendário de recebimentos (visão)',
 'Visão: itens do fluxo de caixa com a data de calendário ajustada a feriados e dia útil.',
 'Calculada de cashflow_items + bank_holidays', 'Agenda de recebimentos, Banco (Cora)'),
('public', 'bank_holidays', 'Financeiro e banco', 'Feriados bancários',
 'Feriados usados para empurrar datas de pagamento para o próximo dia útil.',
 'Cadastro manual', 'Agenda de recebimentos'),
('public', 'bank_transactions', 'Financeiro e banco', 'Extrato bancário (Cora)',
 'Cada movimento da conta: data, entrada/saída, valor, descrição, contraparte.',
 'Integração Cora → bank_registrar_extrato', 'Banco (Cora), DRE, Projeção'),
('public', 'bank_matches', 'Financeiro e banco', 'Conciliação banco × previsto',
 'Liga um movimento do extrato ao recebimento previsto que ele paga (automático ou manual).',
 'Tela Banco (Cora) → bank_vincular / conciliação automática', 'Banco (Cora), Agenda de recebimentos'),
('public', 'bank_sync', 'Financeiro e banco', 'Última sincronização do banco',
 'Quando o extrato foi buscado pela última vez e o resultado.',
 'Integração Cora', 'Banco (Cora), DRE'),
('public', 'dre_regras', 'Financeiro e banco', 'Regras de classificação da DRE',
 'Para cada contraparte (nome normalizado) e tipo (entrada/saída), a categoria da DRE que você escolheu.',
 'Tela DRE → dre_classificar', 'DRE, Projeção'),

-- ---------- Repasse às psicólogas ----------
('public', 'payout_rules', 'Repasse às psicólogas', 'Regras de repasse',
 'Percentual PF/CNPJ e INSS por psicóloga e vigência. Ainda vazia: hoje vem de legado.exencoes.',
 'Futuro módulo de repasse', '—'),
('public', 'payouts', 'Repasse às psicólogas', 'Repasses calculados',
 'Valor bruto, INSS e líquido por psicóloga e mês. Ainda vazia.', 'Futuro módulo de repasse', '—'),
('public', 'inss_ceilings', 'Repasse às psicólogas', 'Teto do INSS',
 'Teto de contribuição do INSS por vigência, usado no cálculo do RPA.', 'Cadastro manual', 'Repasse (RPA)'),
('public', 'fiscal_documents', 'Repasse às psicólogas', 'Documentos fiscais (RPA/NF)',
 'RPAs e notas das psicólogas com cópia dos dados no momento da emissão (CPF/PIX criptografados).',
 'Futuro módulo de repasse', '—'),

-- ---------- Clínica (sistema novo) ----------
('public', 'patients', 'Clínica (sistema novo)', 'Pacientes',
 'Cadastro de pacientes do sistema novo (CPF criptografado). Ainda vazia: hoje os pacientes estão nas planilhas.',
 'Futuro cadastro', '—'),
('public', 'professional_profiles', 'Clínica (sistema novo)', 'Psicólogas',
 'Cadastro das profissionais (CRP, abordagem, idade mínima; CPF/RG/PIX criptografados). Ainda vazia.',
 'Futuro cadastro', '—'),
('public', 'professional_credentials', 'Clínica (sistema novo)', 'Documentos das psicólogas',
 'RG, diploma e outros anexos de cada profissional.', 'Futuro credenciamento', '—'),
('public', 'professional_availability_blocks', 'Clínica (sistema novo)', 'Bloqueios de agenda',
 'Períodos em que a psicóloga não atende (férias, licença).', 'Futuro módulo de agenda', '—'),
('public', 'rooms', 'Clínica (sistema novo)', 'Salas / consultórios',
 'Consultórios da clínica.', 'Futuro módulo de agenda', '—'),
('public', 'appointments', 'Clínica (sistema novo)', 'Agendamentos fixos',
 'Horário fixo paciente × psicóloga × sala × convênio. Ainda vazia: hoje vem de legado.agenda.',
 'Futuro módulo de agenda', '—'),
('public', 'sessions', 'Clínica (sistema novo)', 'Sessões',
 'Cada sessão realizada/falta com valor e situação de faturamento. Ainda vazia: hoje vem de legado.atendimentos_raw.',
 'Futuro módulo de sessões', '—'),
('public', 'waitlist_entries', 'Clínica (sistema novo)', 'Lista de espera',
 'Pacientes aguardando horário: dia/período preferido e idade.', 'Futuro módulo de agenda', '—'),
('public', 'notifications', 'Clínica (sistema novo)', 'Notificações',
 'Avisos gerados para as profissionais sobre agendamentos.', 'Futuro módulo de agenda', '—'),
('public', 'document_declarations', 'Clínica (sistema novo)', 'Declarações de comparecimento',
 'Declarações emitidas para pacientes, com código de verificação.', 'Futuro módulo', '—'),

-- ---------- Sistema e segurança ----------
('public', 'tenants', 'Sistema e segurança', 'Clínicas',
 'Cada clínica no HOPE CORE (hoje só a Clínica Hope). Todas as tabelas com tenant_id são separadas por ela.',
 'Instalação', 'Todo o sistema'),
('public', 'users', 'Sistema e segurança', 'Usuários',
 'Quem entra no HOPE CORE, de qual clínica e com qual papel (owner, manager, admin_staff).',
 'Supabase Auth + cadastro', 'Login e permissões de todas as telas'),
('public', 'platform_admins', 'Sistema e segurança', 'Administradores da plataforma',
 'Usuários com acesso a todas as clínicas (suporte).', 'Cadastro manual', 'Permissões'),
('public', 'audit_log', 'Sistema e segurança', 'Auditoria geral',
 'Registro automático de ações importantes (quem, o quê, quando).', 'Gatilhos e funções do sistema', 'Auditoria'),
('public', 'db_catalogo_tabelas', 'Sistema e segurança', 'Catálogo: descrição das tabelas',
 'As descrições que aparecem nesta tela (para que serve, de onde vem, onde é usada). Edite pela própria tela de cada tabela.',
 'Migrations + tela Banco de dados', 'Banco de dados'),
('public', 'db_catalogo_colunas', 'Sistema e segurança', 'Catálogo: descrição das colunas',
 'Descrição de cada coluna, editável na tela de cada tabela.', 'Tela Banco de dados', 'Banco de dados'),
('public', 'db_alteracoes', 'Sistema e segurança', 'Histórico de alterações pela tela',
 'Toda linha criada, editada ou excluída pela tela Banco de dados: quem, quando, antes e depois.',
 'Gravada automaticamente por db_salvar / db_excluir', 'Banco de dados')
on conflict (esquema, tabela) do nothing;

insert into public.db_catalogo_colunas (esquema, tabela, coluna, descricao) values
('legado', 'planilhas', 'spreadsheet_id', 'ID da planilha no Google Drive'),
('legado', 'planilhas', 'nome_abreviado', 'Nome curto da psicóloga (como aparece nos relatórios)'),
('legado', 'planilhas', 'desligada', 'Psicóloga desligada: a planilha continua no histórico mas sai dos indicadores atuais'),
('legado', 'planilhas', 'ultima_sincronizacao', 'Última vez que o sync recebeu esta planilha'),
('legado', 'atendimentos_raw', 'celulas', 'As células da linha da planilha, na ordem das colunas (A, B, C…)'),
('legado', 'atendimentos_raw', 'linha', 'Número da linha na planilha'),
('legado', 'agenda', 'tipo', 'PACIENTE, LIVRE (💚), BLOQUEADO, RESERVADO ou INDETERMINADO'),
('legado', 'agenda', 'psicologa_linha', 'Linha da psicóloga na aba ID da planilha mãe'),
('public', 'insurance_plans', 'session_value', 'Valor pago por sessão'),
('public', 'insurance_plans', 'payment_days', 'Dias entre a base (envio, liberação ou NF — coluna payment_base) e o pagamento'),
('public', 'insurance_plans', 'payment_business_day', 'Se o pagamento cai no N-ésimo dia útil'),
('public', 'cashflow_items', 'kind', 'entrada ou saida'),
('public', 'cashflow_items', 'status', 'previsto, realizado, glosado ou cancelado'),
('public', 'cashflow_items', 'expected_date', 'Data em que se espera receber/pagar'),
('public', 'cashflow_items', 'realized_date', 'Data em que realmente entrou/saiu no banco'),
('public', 'bank_transactions', 'kind', 'entrada ou saida'),
('public', 'bank_transactions', 'ignored', 'Marcado para não entrar na conciliação'),
('public', 'bank_transactions', 'raw', 'Movimento completo como veio da API do banco'),
('public', 'dre_regras', 'chave', 'Nome da contraparte normalizado (minúsculo, sem acento)'),
('public', 'dre_regras', 'categoria', 'Linha da DRE onde o movimento entra'),
('public', 'insurance_claim_returns', 'gloss_value', 'Valor glosado (não pago) pela operadora'),
('public', 'insurance_claim_returns', 'item_key', 'Chave única do item (guia + data + procedimento)'),
('public', 'users', 'role', 'owner (dono), manager (gestor) ou admin_staff (administrativo)')
on conflict (esquema, tabela, coluna) do nothing;
